security:
    providers:
        user_provider:
            id: SmartAssert\UsersSecurityBundle\Security\UserProvider
    firewalls:
        public:
            pattern: '%users_security_bundle_public_pattern%'
            security: false
        secured:
            pattern:  '%users_security_bundle_secured_pattern%'
            stateless: true
            custom_authenticators:
                - SmartAssert\UsersSecurityBundle\Security\Authenticator
            provider: user_provider
            entry_point: SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint

    access_control:
        - { path: '%users_security_bundle_access_control_path%', roles: ROLE_USER }
