parameters:
  users_security_bundle_base_url: 'http://localhost:9080'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Http\Message\RequestFactoryInterface:
    class: GuzzleHttp\Psr7\HttpFactory

  Psr\Http\Client\ClientInterface:
    class: GuzzleHttp\Client

  GuzzleHttp\Psr7\HttpFactory: ~

  Psr\Http\Message\StreamFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory

  SmartAssert\UsersClient\Client:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'
    public: true
