parameters:
  users_security_bundle_base_url: 'http://localhost:9080'
  test_authentication_provider_bundle_frontend_token_provider_users:
    'user@example.com': 'password'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Psr\Http\Message\RequestFactoryInterface:
    class: GuzzleHttp\Psr7\HttpFactory

  Psr\Http\Client\ClientInterface:
    class: GuzzleHttp\Client
    public: true

  GuzzleHttp\Psr7\HttpFactory: ~

  Psr\Http\Message\StreamFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory

  'request_stack':
    public: true
    class: Symfony\Component\HttpFoundation\RequestStack

  'security.token_storage':
    public: true
    synthetic: true

  SmartAssert\TestAuthenticationProviderBundle\FrontendTokenProvider:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'
      $userCredentials: '%test_authentication_provider_bundle_frontend_token_provider_users%'

  SmartAssert\TestAuthenticationProviderBundle\UserProvider:
    public: true
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\TestAuthenticationProviderBundle\ApiTokenProvider:
    public: true
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\TestAuthenticationProviderBundle\ApiKeyProvider:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'
