parameters:
  users_security_bundle_base_url: '%env(USERS_SERVICE_BASE_URL)%'
  users_security_bundle_firewall_pattern: '%env(USERS_SECURITY_BUNDLE_FIREWALL_PATTERN)%'
  users_security_bundle_access_control_pattern: '%env(USERS_SECURITY_BUNDLE_ACCESS_CONTROL_PATTERN)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties:

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true

  SmartAssert\UsersSecurityBundle\Security\TokenExtractor:
    public: true

  SmartAssert\UsersSecurityBundle\Security\Authenticator:
    public: true

  SmartAssert\UsersClient\Routes:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\UsersClient\RequestBuilder:

  SmartAssert\UsersClient\Client:

  SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint:
    public: true
