parameters:
  users_security_bundle_base_url: '%env(USERS_SECURITY_BUNDLE_BASE_URL)%'
  users_security_bundle_public_pattern: '%env(USERS_SECURITY_BUNDLE_PUBLIC_PATTERN)%'
  users_security_bundle_secured_pattern: '%env(USERS_SECURITY_BUNDLE_SECURED_PATTERN)%'
  users_security_bundle_access_control_path: '%env(USERS_SECURITY_BUNDLE_ACCESS_CONTROL_PATH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\SecurityTokenExtractor\TokenExtractor: ~

  SmartAssert\UsersSecurityBundle\Security\SymfonyRequestTokenExtractor:
    public: true

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true

  SmartAssert\UsersSecurityBundle\Security\Authenticator:
    public: true

  SmartAssert\ServiceClient\ResponseDecoder: ~

  SmartAssert\ServiceClient\Client: ~

  SmartAssert\UsersClient\ObjectFactory: ~

  SmartAssert\UsersClient\Client:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint:
    public: true
