parameters:
  users_service_base_url: '%env(USERS_SERVICE_BASE_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties:

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true

  SmartAssert\UsersSecurityBundle\Security\TokenExtractor:
    public: true

  SmartAssert\UsersSecurityBundle\Security\Authenticator:
    public: true

  SmartAssert\UsersClient\Routes:
    arguments:
      $baseUrl: '%users_service_base_url%'

  SmartAssert\UsersClient\RequestBuilder:

  SmartAssert\UsersClient\Client:

  SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint:
    public: true
