parameters:
  users_security_bundle_base_url: '%env(USERS_SECURITY_BUNDLE_BASE_URL)%'
  users_security_bundle_public_pattern: '%env(USERS_SECURITY_BUNDLE_PUBLIC_PATTERN)%'
  users_security_bundle_secured_pattern: '%env(USERS_SECURITY_BUNDLE_SECURED_PATTERN)%'
  users_security_bundle_access_control_path: '%env(USERS_SECURITY_BUNDLE_ACCESS_CONTROL_PATH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\SecurityTokenExtractor\TokenExtractor: ~

  SmartAssert\UsersSecurityBundle\Security\SymfonyRequestTokenExtractor:
    public: true

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true
    arguments:
      $requestStack: '@request_stack'

  SmartAssert\UsersSecurityBundle\Security\Authenticator:
    public: true

  SmartAssert\ServiceClient\ResponseDecoder: ~

  SmartAssert\ServiceClient\ResponseFactory\ResponseFactory:
    factory: ['SmartAssert\ServiceClient\ResponseFactory\ResponseFactory', 'createFactory']

  SmartAssert\ServiceClient\ExceptionFactory\CurlExceptionFactory: ~

  SmartAssert\ServiceClient\Client: ~

  SmartAssert\UsersClient\ObjectFactory: ~

  SmartAssert\UsersClient\Client:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint:
    public: true

  SmartAssert\UsersSecurityBundle\ArgumentResolver\UserResolver:
    public: true
    arguments:
      $tokenStorage: '@security.token_storage'
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }
