services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties:

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true

  SmartAssert\UsersSecurityBundle\Security\TokenExtractor:
    public: true
