parameters:
  users_security_bundle_base_url: '%env(USERS_SECURITY_BUNDLE_BASE_URL)%'
  users_security_bundle_public_pattern: '%env(USERS_SECURITY_BUNDLE_PUBLIC_PATTERN)%'
  users_security_bundle_secured_pattern: '%env(USERS_SECURITY_BUNDLE_SECURED_PATTERN)%'
  users_security_bundle_access_control_path: '%env(USERS_SECURITY_BUNDLE_ACCESS_CONTROL_PATH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SmartAssert\UsersSecurityBundle\Security\AuthorizationProperties:

  SmartAssert\UsersSecurityBundle\Security\UserProvider:
    public: true

  SmartAssert\UsersSecurityBundle\Security\TokenExtractor:
    public: true

  SmartAssert\UsersSecurityBundle\Security\Authenticator:
    public: true

  SmartAssert\UsersClient\Routes:
    arguments:
      $baseUrl: '%users_security_bundle_base_url%'

  SmartAssert\UsersClient\RequestBuilder:

  SmartAssert\UsersClient\Client:

  SmartAssert\UsersSecurityBundle\Security\AuthenticationEntryPoint:
    public: true
